<a href="https://colab.research.google.com/github/V-Nayak/DataScience_Assignments/blob/main/Assignment_27june.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import hamming_loss, f1_score
import scipy.sparse as sp

In [73]:
# Load the data
train_data = pd.read_csv("/content/drive/MyDrive/Data Science Assignement/AIQoD/train.csv")
train_labels = pd.read_csv("/content/drive/MyDrive/Data Science Assignement/AIQoD/trainLabels.csv")
test_data = pd.read_csv("/content/drive/MyDrive/Data Science Assignement/AIQoD/test.csv")

In [30]:
train_labels.columns

Index(['id', 'y1', 'y2', 'y3', 'y4', 'y5', 'y6', 'y7', 'y8', 'y9', 'y10',
       'y11', 'y12', 'y13', 'y14', 'y15', 'y16', 'y17', 'y18', 'y19', 'y20',
       'y21', 'y22', 'y23', 'y24', 'y25', 'y26', 'y27', 'y28', 'y29', 'y30',
       'y31', 'y32', 'y33'],
      dtype='object')

In [28]:
# Load data into pandas DataFrames
#train_df = pd.read_csv('train.csv')
#labels_df = pd.read_csv('trainLabels.csv')

# Assuming 'Hashed_Column' is the common identifier
merged_df = pd.merge(train_data, train_labels, on='id')

merged_df

id   x1   x2                                            x3  \
0        1   NO   NO  dqOiM6yBYgnVSezBRiQXs9bvOFnRqrtIoXRIElxD7g8=   
1        2  NaN  NaN                                           NaN   
2        3   NO   NO  ib4VpsEsqJHzDiyL0dZLQ+xQzDPrkxE+9T3mx5fv2wI=   
3        4  YES   NO  BfrqME7vdLw3suQp6YAT16W2piNUmpKhMzuDrVrFQ4w=   
4        5   NO   NO  RTjsrrR8DTlJyaIP9Q3Z8s0zseqlVQTrlSe97GCWfbk=   
...    ...  ...  ...                                           ...   
9994  9995   NO   NO  jComfqYTXYSeH3GvqcOhwPmldb+BCdVJDKKDNkdtw2w=   
9995  9996   NO   NO  Pr5enXjzVzVjZziZxrDcgnyu6CLUftmEbnp6TctyJbU=   
9996  9997  YES  YES  9Avs0tL1zvH7Xx41z2UqrXs11/4IWLmqRAodLt/SKjQ=   
9997  9998   NO   NO  9zkXU3f6YnRPjsWi3lKSCLseIGrleg00tpRI4OplABw=   
9998  9999  YES  YES  MZZbXga8gvaCBqWpzrh2iKdOkcsz/bG/z4BVjUnqWT0=   

                                                x4        x5        x6  \
0     GNjrXXA3SxbgD0dTRblAPO9jFJ7AIaZnu/f48g5XSUk=  0.576561  0.073139   
1                                              NaN  0.000000  0.000000   
2     X6dDAI/DZOWvu0Dg6gCgRoNr2vTUz/mc4SdHTNUPS38=  1.341803  0.051422   
3     YGCdISifn4fLao/ASKdZFhGIq23oqzfSbUVb6px1pig=  0.653912  0.041471   
4     3yK2OPj1uYDsoMgsxsjY1FxXkOllD8Xfh20VYGqT+nU=  1.415919  0.000000   
...                                            ...       ...       ...   
9994  Kr2CC15nSwDjdpyAeVh4vOuIaHuC/Q7cL9BAK28JoG8=  1.207136  0.082855   
9995  YvZUuCDjLu9VvkCdBWgARWQrvm+FSXgxp0zIrMjcLBc=  1.414798  0.000000   
9996  WV5vAHFyqkeuyFB5KVNGFOBuwjkUGKYc8wh9QfpVzAA=  1.413677  0.000000   
9997  gOZBAoajyr6i7GgON0N7q5+KE4JTwH3OUM0lZOWMuG8=  1.294118  0.000000   
9998  YvZUuCDjLu9VvkCdBWgARWQrvm+FSXgxp0zIrMjcLBc=  0.660897  0.042735   

            x7        x8        x9  ... y24 y25 y26 y27 y28  y29  y30  y31  \
0     0.481394  0.115697  0.472474  ...   0   0   0   0   0    0    0    0   
1     0.000000  0.000000  0.000000  ...   0   0   0   0   0    0    0    0   
2     0.935572  0.041440  0.501710  ...   0   0   0   0   0    0    0    0   
3     0.940787  0.090851  0.556564  ...   0   0   0   0   0    0    0    0   
4     1.000000  0.000000  0.375297  ...   0   0   0   0   0    0    0    0   
...        ...       ...       ...  ...  ..  ..  ..  ..  ..  ...  ...  ...   
9994  0.918960  0.313880  0.495189  ...   0   0   0   0   0    0    0    0   
9995  1.000000  0.000000  0.357369  ...   0   0   0   0   0    0    0    0   
9996  1.000000  0.000000  0.668517  ...   0   0   0   0   0    0    0    0   
9997  1.000000  0.000000  0.570707  ...   0   0   0   0   0    0    0    0   
9998  0.946581  0.086966  0.510278  ...   0   0   0   0   0    0    0    0   

      y32  y33  
0       0    1  
1       1    0  
2       0    0  
3       0    1  
4       0    1  
...   ...  ...  
9994    0    0  
9995    0    1  
9996    0    0  
9997    0    1  
9998    0    1  

[9999 rows x 179 columns]

In [31]:
# Assuming the labels are in columns 'Label1', 'Label2', ..., 'LabelN'
X = merged_df.drop(['id', 'y1', 'y2', 'y3', 'y4', 'y5', 'y6', 'y7', 'y8', 'y9', 'y10',
       'y11', 'y12', 'y13', 'y14', 'y15', 'y16', 'y17', 'y18', 'y19', 'y20',
       'y21', 'y22', 'y23', 'y24', 'y25', 'y26', 'y27', 'y28', 'y29', 'y30',
       'y31', 'y32', 'y33'], axis=1)  # Drop ID and label columns from features
y = merged_df[['id', 'y1', 'y2', 'y3', 'y4', 'y5', 'y6', 'y7', 'y8', 'y9', 'y10',
       'y11', 'y12', 'y13', 'y14', 'y15', 'y16', 'y17', 'y18', 'y19', 'y20',
       'y21', 'y22', 'y23', 'y24', 'y25', 'y26', 'y27', 'y28', 'y29', 'y30',
       'y31', 'y32', 'y33']]  # Select multi-label columns as targets

In [33]:
# Inspect the data to understand its structure
print(X.head())
print(y.head())


    x1   x2                                            x3  \
0   NO   NO  dqOiM6yBYgnVSezBRiQXs9bvOFnRqrtIoXRIElxD7g8=   
1  NaN  NaN                                           NaN   
2   NO   NO  ib4VpsEsqJHzDiyL0dZLQ+xQzDPrkxE+9T3mx5fv2wI=   
3  YES   NO  BfrqME7vdLw3suQp6YAT16W2piNUmpKhMzuDrVrFQ4w=   
4   NO   NO  RTjsrrR8DTlJyaIP9Q3Z8s0zseqlVQTrlSe97GCWfbk=   

                                             x4        x5        x6        x7  \
0  GNjrXXA3SxbgD0dTRblAPO9jFJ7AIaZnu/f48g5XSUk=  0.576561  0.073139  0.481394   
1                                           NaN  0.000000  0.000000  0.000000   
2  X6dDAI/DZOWvu0Dg6gCgRoNr2vTUz/mc4SdHTNUPS38=  1.341803  0.051422  0.935572   
3  YGCdISifn4fLao/ASKdZFhGIq23oqzfSbUVb6px1pig=  0.653912  0.041471  0.940787   
4  3yK2OPj1uYDsoMgsxsjY1FxXkOllD8Xfh20VYGqT+nU=  1.415919  0.000000  1.000000   

         x8        x9  x10  ... x136   x137  x138  x139  x140  x141  x142  \
0  0.115697  0.472474  YES  ...  0.0  0.810  3306  4676   YES    NO  

In [34]:
# Define a mapping dictionary for conversion
bool_map = {'YES': True, 'NO': False}

# Iterate over each column in the DataFrame
for col in X.columns:
    # Check if column contains 'yes' and 'no' values (object dtype)
    if X[col].dtype == 'object' and X[col].isin(['YES', 'NO',]).all() or X[col].dtype == 'object' and X[col].isin(['YES', 'NO',np.NaN]).all():
        # Convert 'yes'/'no' values to boolean dtype using map
        X[col] =X[col].map(bool_map).astype(bool)



In [35]:
X

x1     x2                                            x3  \
0     False  False  dqOiM6yBYgnVSezBRiQXs9bvOFnRqrtIoXRIElxD7g8=   
1      True   True                                           NaN   
2     False  False  ib4VpsEsqJHzDiyL0dZLQ+xQzDPrkxE+9T3mx5fv2wI=   
3      True  False  BfrqME7vdLw3suQp6YAT16W2piNUmpKhMzuDrVrFQ4w=   
4     False  False  RTjsrrR8DTlJyaIP9Q3Z8s0zseqlVQTrlSe97GCWfbk=   
...     ...    ...                                           ...   
9994  False  False  jComfqYTXYSeH3GvqcOhwPmldb+BCdVJDKKDNkdtw2w=   
9995  False  False  Pr5enXjzVzVjZziZxrDcgnyu6CLUftmEbnp6TctyJbU=   
9996   True   True  9Avs0tL1zvH7Xx41z2UqrXs11/4IWLmqRAodLt/SKjQ=   
9997  False  False  9zkXU3f6YnRPjsWi3lKSCLseIGrleg00tpRI4OplABw=   
9998   True   True  MZZbXga8gvaCBqWpzrh2iKdOkcsz/bG/z4BVjUnqWT0=   

                                                x4        x5        x6  \
0     GNjrXXA3SxbgD0dTRblAPO9jFJ7AIaZnu/f48g5XSUk=  0.576561  0.073139   
1                                              NaN  0.000000  0.000000   
2     X6dDAI/DZOWvu0Dg6gCgRoNr2vTUz/mc4SdHTNUPS38=  1.341803  0.051422   
3     YGCdISifn4fLao/ASKdZFhGIq23oqzfSbUVb6px1pig=  0.653912  0.041471   
4     3yK2OPj1uYDsoMgsxsjY1FxXkOllD8Xfh20VYGqT+nU=  1.415919  0.000000   
...                                            ...       ...       ...   
9994  Kr2CC15nSwDjdpyAeVh4vOuIaHuC/Q7cL9BAK28JoG8=  1.207136  0.082855   
9995  YvZUuCDjLu9VvkCdBWgARWQrvm+FSXgxp0zIrMjcLBc=  1.414798  0.000000   
9996  WV5vAHFyqkeuyFB5KVNGFOBuwjkUGKYc8wh9QfpVzAA=  1.413677  0.000000   
9997  gOZBAoajyr6i7GgON0N7q5+KE4JTwH3OUM0lZOWMuG8=  1.294118  0.000000   
9998  YvZUuCDjLu9VvkCdBWgARWQrvm+FSXgxp0zIrMjcLBc=  0.660897  0.042735   

            x7        x8        x9    x10  ...  x136   x137  x138  x139  \
0     0.481394  0.115697  0.472474   True  ...   0.0  0.810  3306  4676   
1     0.000000  0.000000  0.000000   True  ...   0.0  0.510  4678  3306   
2     0.935572  0.041440  0.501710  False  ...   0.0  0.850  4678  3306   
3     0.940787  0.090851  0.556564   True  ...   0.0  0.945  3306  4678   
4     1.000000  0.000000  0.375297  False  ...   0.0  1.000  1263   892   
...        ...       ...       ...    ...  ...   ...    ...   ...   ...   
9994  0.918960  0.313880  0.495189  False  ...   0.0  0.810  4677  3307   
9995  1.000000  0.000000  0.357369   True  ...   0.0  1.000  1262   892   
9996  1.000000  0.000000  0.668517   True  ...   0.0  1.000  1261   892   
9997  1.000000  0.000000  0.570707  False  ...   1.0  1.000  1188   918   
9998  0.946581  0.086966  0.510278   True  ...   0.0  0.880  3308  4680   

       x140   x141   x142  x143      x144      x145  
0      True  False   True     2  0.375535  0.464610  
1      True  False   True     4  0.741682  0.593630  
2     False  False  False     1  0.776467  0.493159  
3     False  False   True     3  0.168234  0.546582  
4     False  False  False     1  0.246637  0.361045  
...     ...    ...    ...   ...       ...       ...  
9994   True  False   True     1  0.502268  0.486637  
9995   True  False   True    15  0.890135  0.346276  
9996   True  False   True     5  0.726457  0.659001  
9997  False  False  False     3  0.450980  0.561448  
9998   True  False   True     0  0.604274  0.499395  

[9999 rows x 145 columns]

In [10]:
# Check for NaN values
nan_counts = train_data.isna().sum()
print(nan_counts)

id         0
x1         0
x2         0
x3      1426
x4      1426
        ... 
x141       0
x142       0
x143       0
x144       0
x145       0
Length: 146, dtype: int64


In [36]:
# Define the hashed columns and exclude them from the features used for training
hashed_columns = ['x3', 'x4', 'x34', 'x35', 'x61', 'x64', 'x65', 'x91', 'x94', 'x95']

# Define other features (excluding the hashed columns)
other_features = [col for col in X.columns if col not in hashed_columns]


In [37]:
other_features

['x1',
 'x2',
 'x5',
 'x6',
 'x7',
 'x8',
 'x9',
 'x10',
 'x11',
 'x12',
 'x13',
 'x14',
 'x15',
 'x16',
 'x17',
 'x18',
 'x19',
 'x20',
 'x21',
 'x22',
 'x23',
 'x24',
 'x25',
 'x26',
 'x27',
 'x28',
 'x29',
 'x30',
 'x31',
 'x32',
 'x33',
 'x36',
 'x37',
 'x38',
 'x39',
 'x40',
 'x41',
 'x42',
 'x43',
 'x44',
 'x45',
 'x46',
 'x47',
 'x48',
 'x49',
 'x50',
 'x51',
 'x52',
 'x53',
 'x54',
 'x55',
 'x56',
 'x57',
 'x58',
 'x59',
 'x60',
 'x62',
 'x63',
 'x66',
 'x67',
 'x68',
 'x69',
 'x70',
 'x71',
 'x72',
 'x73',
 'x74',
 'x75',
 'x76',
 'x77',
 'x78',
 'x79',
 'x80',
 'x81',
 'x82',
 'x83',
 'x84',
 'x85',
 'x86',
 'x87',
 'x88',
 'x89',
 'x90',
 'x92',
 'x93',
 'x96',
 'x97',
 'x98',
 'x99',
 'x100',
 'x101',
 'x102',
 'x103',
 'x104',
 'x105',
 'x106',
 'x107',
 'x108',
 'x109',
 'x110',
 'x111',
 'x112',
 'x113',
 'x114',
 'x115',
 'x116',
 'x117',
 'x118',
 'x119',
 'x120',
 'x121',
 'x122',
 'x123',
 'x124',
 'x125',
 'x126',
 'x127',
 'x128',
 'x129',
 'x130',
 'x131',
 'x132'

In [38]:
 X[other_features]


x1     x2        x5        x6        x7        x8        x9    x10  \
0     False  False  0.576561  0.073139  0.481394  0.115697  0.472474   True   
1      True   True  0.000000  0.000000  0.000000  0.000000  0.000000   True   
2     False  False  1.341803  0.051422  0.935572  0.041440  0.501710  False   
3      True  False  0.653912  0.041471  0.940787  0.090851  0.556564   True   
4     False  False  1.415919  0.000000  1.000000  0.000000  0.375297  False   
...     ...    ...       ...       ...       ...       ...       ...    ...   
9994  False  False  1.207136  0.082855  0.918960  0.313880  0.495189  False   
9995  False  False  1.414798  0.000000  1.000000  0.000000  0.357369   True   
9996   True   True  1.413677  0.000000  1.000000  0.000000  0.668517   True   
9997  False  False  1.294118  0.000000  1.000000  0.000000  0.570707  False   
9998   True   True  0.660897  0.042735  0.946581  0.086966  0.510278   True   

        x11    x12  ...  x136   x137  x138  x139   x140   x141   x142  x143  \
0     False  False  ...   0.0  0.810  3306  4676   True  False   True     2   
1      True   True  ...   0.0  0.510  4678  3306   True  False   True     4   
2     False   True  ...   0.0  0.850  4678  3306  False  False  False     1   
3     False  False  ...   0.0  0.945  3306  4678  False  False   True     3   
4     False   True  ...   0.0  1.000  1263   892  False  False  False     1   
...     ...    ...  ...   ...    ...   ...   ...    ...    ...    ...   ...   
9994  False  False  ...   0.0  0.810  4677  3307   True  False   True     1   
9995  False  False  ...   0.0  1.000  1262   892   True  False   True    15   
9996  False  False  ...   0.0  1.000  1261   892   True  False   True     5   
9997  False  False  ...   1.0  1.000  1188   918  False  False  False     3   
9998  False  False  ...   0.0  0.880  3308  4680   True  False   True     0   

          x144      x145  
0     0.375535  0.464610  
1     0.741682  0.593630  
2     0.776467  0.493159  
3     0.168234  0.546582  
4     0.246637  0.361045  
...        ...       ...  
9994  0.502268  0.486637  
9995  0.890135  0.346276  
9996  0.726457  0.659001  
9997  0.450980  0.561448  
9998  0.604274  0.499395  

[9999 rows x 135 columns]

In [48]:
X_subset =  X[other_features].head(100)
X_subset

x1     x2        x5        x6        x7        x8        x9    x10  \
0   False  False  0.576561  0.073139  0.481394  0.115697  0.472474   True   
1    True   True  0.000000  0.000000  0.000000  0.000000  0.000000   True   
2   False  False  1.341803  0.051422  0.935572  0.041440  0.501710  False   
3    True  False  0.653912  0.041471  0.940787  0.090851  0.556564   True   
4   False  False  1.415919  0.000000  1.000000  0.000000  0.375297  False   
..    ...    ...       ...       ...       ...       ...       ...    ...   
95  False  False  1.111176  0.109118  0.812941  1.094412  0.851591  False   
96  False  False  0.211719  0.186047  0.935367  0.138025  0.131253  False   
97  False  False  1.065336  0.058984  0.869933  0.988808  0.751712   True   
98  False  False  0.836471  0.127059  0.846471  0.786471  0.625455   True   
99   True   True  0.000000  0.000000  0.000000  0.000000  0.000000   True   

      x11    x12  ...  x136   x137  x138  x139   x140   x141   x142  x143  \
0   False  False  ...   0.0  0.810  3306  4676   True  False   True     2   
1    True   True  ...   0.0  0.510  4678  3306   True  False   True     4   
2   False   True  ...   0.0  0.850  4678  3306  False  False  False     1   
3   False  False  ...   0.0  0.945  3306  4678  False  False   True     3   
4   False   True  ...   0.0  1.000  1263   892  False  False  False     1   
..    ...    ...  ...   ...    ...   ...   ...    ...    ...    ...   ...   
95  False  False  ...   0.0  0.770  4400  3400   True  False   True    14   
96  False  False  ...   0.0  0.890  4678  3311  False  False  False     2   
97  False   True  ...   5.0  0.860  4672  3306   True  False   True     5   
98  False  False  ...   0.0  0.460  4400  3400  False  False  False     0   
99   True   True  ...   0.0  1.000  1188   918   True  False   True     2   

        x144      x145  
0   0.375535  0.464610  
1   0.741682  0.593630  
2   0.776467  0.493159  
3   0.168234  0.546582  
4   0.246637  0.361045  
..       ...       ...  
95  0.722647  0.846591  
96  0.478103  0.131253  
97  0.770115  0.744007  
98  0.597647  0.617045  
99  0.925926  0.792088  

[100 rows x 135 columns]

In [49]:
y_subset = y.head(100)
y_subset

id  y1  y2  y3  y4  y5  y6  y7  y8  y9  ...  y24  y25  y26  y27  y28  \
0     1   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
1     2   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
2     3   0   0   1   0   0   0   0   0   0  ...    0    0    0    0    0   
3     4   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
4     5   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
95   96   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
96   97   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
97   98   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
98   99   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
99  100   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   

    y29  y30  y31  y32  y33  
0     0    0    0    0    1  
1     0    0    0    1    0  
2     0    0    0    0    0  
3     0    0    0    0    1  
4     0    0    0    0    1  
..  ...  ...  ...  ...  ...  
95    0    0    0    0    1  
96    0    0    0    0    1  
97    0    0    0    0    1  
98    0    0    0    0    1  
99    0    1    0    0    0  

[100 rows x 34 columns]

In [79]:
# Define the hashed columns and exclude them from the features used for training
hashed_columns = ['x3', 'x4', 'x34', 'x35', 'x61', 'x64', 'x65', 'x91', 'x94', 'x95']

# Define other features (excluding the hashed columns)
other_features = [col for col in test_data.columns if col not in hashed_columns]

In [80]:
test_data[other_features].head(5)

id     x1     x2        x5        x6        x7        x8        x9  \
0  1698001  False  False  1.414798  0.000000  1.000000  0.000000  0.202060   
1  1698002  False  False  0.832679  0.049834  0.945938  0.317427  0.482021   
2  1698003  False  False  1.415919  0.000000  1.000000  0.000000  0.703088   
3  1698004   True   True  0.000000  0.000000  0.000000  0.000000  0.000000   
4  1698005  False  False  1.129212  0.087020  0.814240  1.112804  0.874318   

     x10    x11  ...  x136      x137  x138  x139   x140   x141   x142  x143  \
0  False  False  ...   0.0  1.000000  1262   892  False  False  False     0   
1   True  False  ...   1.0  0.866667  4672  3311  False  False  False     5   
2  False  False  ...  -1.0  1.000000  1263   892  False  False  False     8   
3   True   True  ...   0.0  0.870000  4672  3306   True  False   True     0   
4  False  False  ...   0.0  0.870000  4400  3413   True  False   True     2   

       x144      x145  
0  0.089686  0.193344  
1  0.945032  0.471318  
2  0.557175  0.693587  
3  0.870538  0.405822  
4  0.224729  0.870909  

[5 rows x 136 columns]

In [81]:
# Define a mapping dictionary for conversion
bool_map = {'YES': True, 'NO': False}

# Iterate over each column in the DataFrame
for col in test_data.columns:
    # Check if column contains 'yes' and 'no' values (object dtype)
    if test_data[col].dtype == 'object' and test_data[col].isin(['YES', 'NO',]).all() or test_data[col].dtype == 'object' and test_data[col].isin(['YES', 'NO',np.NaN]).all():

    # Convert 'yes'/'no' values to boolean dtype using map
     test_data[col] =test_data[col].map(bool_map).astype(bool)

In [82]:
test_data[other_features]

id     x1     x2        x5        x6        x7        x8        x9  \
0     1698001  False  False  1.414798  0.000000  1.000000  0.000000  0.202060   
1     1698002  False  False  0.832679  0.049834  0.945938  0.317427  0.482021   
2     1698003  False  False  1.415919  0.000000  1.000000  0.000000  0.703088   
3     1698004   True   True  0.000000  0.000000  0.000000  0.000000  0.000000   
4     1698005  False  False  1.129212  0.087020  0.814240  1.112804  0.874318   
...       ...    ...    ...       ...       ...       ...       ...       ...   
1995  1699996  False  False  1.294118  0.000000  1.000000  0.000000  0.164141   
1996  1699997  False  False  1.020217  0.583944  0.625842  1.003516  0.791136   
1997  1699998  False  False  0.354706  0.550882  0.930882  0.207941  0.207500   
1998  1699999  False  False  1.220588  0.102059  0.326176  1.213824  0.942955   
1999  1700000  False  False  0.699425  0.100695  0.793771  0.183550  0.420569   

        x10    x11  ...  x136      x137  x138  x139   x140   x141   x142  \
0     False  False  ...   0.0  1.000000  1262   892  False  False  False   
1      True  False  ...   1.0  0.866667  4672  3311  False  False  False   
2     False  False  ...  -1.0  1.000000  1263   892  False  False  False   
3      True   True  ...   0.0  0.870000  4672  3306   True  False   True   
4     False  False  ...   0.0  0.870000  4400  3413   True  False   True   
...     ...    ...  ...   ...       ...   ...   ...    ...    ...    ...   
1995   True  False  ...   0.0  1.000000  1188   918   True  False   True   
1996   True  False  ...   0.0  0.720000  4400  3413   True  False   True   
1997  False  False  ...   0.0  0.845000  4400  3400  False  False  False   
1998  False  False  ...   1.5  0.676667  4400  3400  False  False  False   
1999  False  False  ...   0.0  0.580000  4677  3307  False  False  False   

      x143      x144      x145  
0        0  0.089686  0.193344  
1        5  0.945032  0.471318  
2        8  0.557175  0.693587  
3        0  0.870538  0.405822  
4        2  0.224729  0.870909  
...    ...       ...       ...  
1995     2  0.198257  0.155724  
1996     0  0.582479  0.778864  
1997     5  0.930588  0.201591  
1998     2  0.256471  0.938182  
1999     0  0.190807  0.416506  

[2000 rows x 136 columns]

### ***Here we have choosen 100 rows for reducing memory usage ***

In [83]:
# Separate the features and labels
X_train = X_subset
y_train = y_subset

In [84]:
# Scaling other features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(test_data[other_features])

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- id


In [54]:
# If there are text features, apply TF-IDF vectorization (example)
# Assuming 'text_column' is a column containing text data
# vectorizer = TfidfVectorizer()
# X_train_text = vectorizer.fit_transform(X_train['text_column'])
# X_test_text = vectorizer.transform(test_data['text_column'])



# Combine features if text features are included
# X_train_combined = sp.hstack((X_train_text, X_train_scaled))
# X_test_combined = sp.hstack((X_test_text, X_test_scaled))

# For simplicity, if no text feature, just use the scaled features
X_train_combined = X_train_scaled
X_test_combined = X_test_scaled

In [55]:
# Train-test split for validation
X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(X_train_combined, y_train, test_size=0.2, random_state=42)

In [56]:
# Model training
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
multi_target_rf = MultiOutputClassifier(rf_classifier, n_jobs=-1)
multi_target_rf.fit(X_train_split, y_train_split)

MultiOutputClassifier(estimator=RandomForestClassifier(random_state=42),
                      n_jobs=-1)

In [61]:
# Model evaluation
y_val_pred = multi_target_rf.predict(X_val_split)

y_val_pred

array([[15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  1],
       [29,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [70,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  1],
       [86,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  1],
       [10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  1],
       [90,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  1],
       [43,  0,  0,  0,  0,  0,  0

In [62]:
# Predictions on the test set
y_test_pred = multi_target_rf.predict(X_test_combined)
y_test_pred_proba = multi_target_rf.predict_proba(X_test_combined)

In [71]:
# Prepare the submission file
submission = []
for i in range(len(test_data)):
    for j in range(len(y_test_pred_proba)):
        submission.append(f"{i+1}_y{j+1},{y_test_pred_proba[j][i]}")

submission_df = pd.DataFrame(submission, columns=["pred"])
submission_df.to_csv('sampleSubmission.csv', index=False)


In [72]:
submission_df

pred
0      1_y1,[0.   0.   0.01 0.03 0.   0.   0.   0.   ...
1                                              1_y2,[1.]
2                                              1_y3,[1.]
3                                           1_y4,[1. 0.]
4                                              1_y5,[1.]
...                                                  ...
67995                               2000_y30,[0.98 0.02]
67996                                   2000_y31,[1. 0.]
67997                               2000_y32,[0.99 0.01]
67998                                   2000_y33,[1. 0.]
67999                               2000_y34,[0.39 0.61]

[68000 rows x 1 columns]

In [65]:
y_test_pred_proba

[array([[0.  , 0.  , 0.01, ..., 0.  , 0.  , 0.  ],
        [0.  , 0.03, 0.03, ..., 0.05, 0.03, 0.  ],
        [0.  , 0.  , 0.  , ..., 0.02, 0.  , 0.  ],
        ...,
        [0.  , 0.  , 0.  , ..., 0.01, 0.02, 0.03],
        [0.02, 0.  , 0.  , ..., 0.01, 0.04, 0.  ],
        [0.06, 0.01, 0.  , ..., 0.  , 0.05, 0.  ]]),
 array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]]),
 array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]]),
 array([[1.  , 0.  ],
        [0.95, 0.05],
        [1.  , 0.  ],
        ...,
        [0.93, 0.07],
        [0.99, 0.01],
        [1.  , 0.  ]]),
 array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]]),
 array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]]),
 array([[1.  , 0.  ],
        [0.66, 0.34],
        [1.  , 0.  ],
        ...,
        [0.44, 0.56],
        [0.92, 0.08],
        [1.  